apiVersion: v1
description: A Helm chart for KubeInvaders
name: kubeinvaders
appVersion: 1.9.7
version: 1.9.7
home: https://github.com/alex-j-davison/kubeinvaders
image: https://github.com/alex-j-davison/kubeinvaders/blob/master/kubeinvaders.svg
sources:
- https://github.com/alex-j-davison/kubeinvaders
maintainers:
- name: alex-j-davison
  email: alexdav@cisco.com 
